import{describe,expect,it}from"vitest";
import type{InventoryItem}from"../domain/personalization";
import{emptyPromotion,type PromotionItem}from"../domain/promotion";
import{emptyRecipe,type Recipe}from"../domain/recipe";
import{emptyWeeklySelections,isExternalRecipeEligibleForWeeklyRecommendation,recipeToRecommendation,type WeeklyRecommendation}from"../domain/weeklyPlan";
import{buildShoppingList,makeWeeklySelection,parseIngredientQuantity,scaleIngredient}from"./generator";
const now=new Date().toISOString();
function recipe(changes:Partial<Recipe>={}):Recipe{return{...emptyRecipe(),id:"r",title:"Kycklinggryta",sourceType:"personal",servings:4,originalServings:4,mealTypes:["Lunch","Middag"],primaryProtein:"Kyckling",caloriesPerServing:600,proteinGramsPerServing:45,carbsGramsPerServing:60,fatGramsPerServing:18,nutritionComplete:true,nutritionEligible:false,nutritionSource:"unknown",favorite:false,timesCooked:0,createdAt:now,updatedAt:now,ingredients:[{id:"i",name:"Kycklingfilé",quantity:"1200",unit:"g"}],instructions:[],...changes}}
function inventory(changes:Partial<InventoryItem>={}):InventoryItem{return{id:"i",displayName:"Kycklingfilé",normalizedName:"kycklingfile",quantity:1200,unit:"g",location:"freezer",notes:"",useFirst:false,createdAt:now,updatedAt:now,...changes}}
function promo(ignored=false):PromotionItem{return{...emptyPromotion(),id:"p",flyerId:"f",displayName:"Kycklingfilé",normalizedName:"kycklingfile",ignored,createdAt:now,updatedAt:now}}
const context=(overrides:any={})=>({dailyCalories:2500,proteinPriority:"high",promotions:[],inventory:[],...overrides});
function recommendation(ingredients:WeeklyRecommendation["ingredients"],category:"lunch"|"dinner"="lunch"):WeeklyRecommendation{return{id:category,category,title:"R",sourceName:"Mina recept",sourceUrl:"",sourceType:"personal",calories:600,protein:45,carbs:60,fat:18,servings:4,originalServings:4,ingredients,primaryProtein:"Kyckling",cuisine:"",favorite:false,score:1,campaignRelevance:0,reasons:[]}}
describe("weekly eligibility",()=>{const external={sourceType:"external",nutritionEligible:true,nutritionSource:"published",caloriesPerServing:600,proteinGramsPerServing:45,carbsGramsPerServing:60,fatGramsPerServing:18};it("kräver fyra trovärdiga makron",()=>{expect(isExternalRecipeEligibleForWeeklyRecommendation(external)).toBe(true);for(const key of["caloriesPerServing","proteinGramsPerServing","carbsGramsPerServing","fatGramsPerServing"]as const)expect(isExternalRecipeEligibleForWeeklyRecommendation({...external,[key]:null})).toBe(false)});it("behåller personliga recept utan kompletta makron valbara",()=>{expect(recipeToRecommendation(recipe({proteinGramsPerServing:undefined}),"lunch",context())?.sourceName).toBe("Mina recept")})});
describe("deterministic scoring",()=>{it("ignorerad kampanj ger noll signal",()=>{const base=recipeToRecommendation(recipe(),"lunch",context())!,ignored=recipeToRecommendation(recipe(),"lunch",context({promotions:[promo(true)]}))!;expect(ignored.score).toBe(base.score)});it("kampanj, hemma, use-first och favorit påverkar",()=>{const base=recipeToRecommendation(recipe(),"lunch",context())!,campaign=recipeToRecommendation(recipe(),"lunch",context({promotions:[promo()]}))!,first=recipeToRecommendation(recipe({favorite:true}),"lunch",context({inventory:[inventory({useFirst:true})]}))!;expect(campaign.score).toBeGreaterThan(base.score);expect(first.score).toBeGreaterThan(base.score)})});
describe("scaling and shopping",()=>{it("skalar sex till fyra portioner",()=>expect(scaleIngredient("900",6,4)).toBe(600));it("tolkar bråktal",()=>{expect(parseIngredientQuantity("1 1/2")).toBe(1.5);expect(parseIngredientQuantity("½")).toBe(.5)});it("kombinerar alla val före lageravdrag",()=>{const selections=emptyWeeklySelections();selections.lunch=[makeWeeklySelection(recommendation([{name:"Ris",quantity:"400",unit:"g"}]),3)];selections.dinner=[makeWeeklySelection(recommendation([{name:"Ris",quantity:"400",unit:"g"}],"dinner"),2)];const row=buildShoppingList(selections,[inventory({displayName:"Ris",normalizedName:"ris",quantity:200})],[])[0];expect(row.requiredQuantity).toBe(500);expect(row.buyQuantity).toBe(300)});it("lager som täcker behov ger köp noll",()=>{const selections=emptyWeeklySelections();selections.lunch=[makeWeeklySelection(recommendation([{name:"Kycklingfilé",quantity:"800",unit:"g"}]),3)];const row=buildShoppingList(selections,[inventory({quantity:600})],[promo()])[0];expect(row.requiredQuantity).toBe(600);expect(row.buyQuantity).toBe(0);expect(row.promotion?.displayName).toBe("Kycklingfilé")});it("okända originalportioner ger ingen falsk skalning",()=>{const selections=emptyWeeklySelections(),rec={...recommendation([{name:"Vitlök",quantity:"2",unit:"st"}]),originalServings:null,servings:null};selections.lunch=[makeWeeklySelection(rec,4)];const row=buildShoppingList(selections,[],[])[0];expect(row.requiredQuantity).toBeNull();expect(row.warning).toContain("Originalportioner")})});
