import{describe,expect,it}from"vitest";import type{InventoryItem}from"../domain/personalization";import{emptyPromotion,type PromotionItem}from"../domain/promotion";import{emptyRecipe,type Recipe}from"../domain/recipe";import{isExternalRecipeEligibleForWeeklyRecommendation,recipeToRecommendation,type WeeklyRecommendation}from"../domain/weeklyPlan";import{buildShoppingList,scaleIngredient}from"./generator";
const now=new Date().toISOString();
function recipe(changes:Partial<Recipe>={}):Recipe{return{...emptyRecipe(),id:"r",title:"Kycklinggryta",sourceType:"personal",servings:4,mealTypes:["Lunch","Middag"],primaryProtein:"Kyckling",caloriesPerServing:600,proteinGramsPerServing:45,carbsGramsPerServing:60,fatGramsPerServing:18,nutritionComplete:true,nutritionEligible:false,nutritionSource:"unknown",favorite:false,timesCooked:0,createdAt:now,updatedAt:now,ingredients:[{id:"i",name:"Kycklingfilé",quantity:"1200",unit:"g"}],instructions:[],...changes}}
function inventory(changes:Partial<InventoryItem>={}):InventoryItem{return{id:"i",displayName:"Kycklingfilé",normalizedName:"kycklingfile",quantity:1200,unit:"g",location:"freezer",notes:"",useFirst:false,createdAt:now,updatedAt:now,...changes}}
function promo(ignored=false):PromotionItem{return{...emptyPromotion(),id:"p",flyerId:"f",displayName:"Kycklingfilé",normalizedName:"kycklingfile",ignored,createdAt:now,updatedAt:now}}
const context=(overrides:any={})=>({dailyCalories:2500,proteinPriority:"high",promotions:[],inventory:[],...overrides});
describe("weekly eligibility",()=>{const external={sourceType:"external",nutritionEligible:true,nutritionSource:"published",caloriesPerServing:600,proteinGramsPerServing:45,carbsGramsPerServing:60,fatGramsPerServing:18};it("kräver fyra trovärdiga makron och försvarar mot stale boolean",()=>{expect(isExternalRecipeEligibleForWeeklyRecommendation(external)).toBe(true);for(const key of["caloriesPerServing","proteinGramsPerServing","carbsGramsPerServing","fatGramsPerServing"]as const)expect(isExternalRecipeEligibleForWeeklyRecommendation({...external,[key]:null})).toBe(false);expect(isExternalRecipeEligibleForWeeklyRecommendation({...external,fatGramsPerServing:-1})).toBe(false)});it("behåller personliga recept utan kompletta makron valbara",()=>{expect(recipeToRecommendation(recipe({proteinGramsPerServing:undefined}),"lunch",context())?.sourceName).toBe("Mina recept")})});
describe("deterministic scoring",()=>{it("ignorerad kampanj ger noll signal",()=>{const base=recipeToRecommendation(recipe(),"lunch",context())!,ignored=recipeToRecommendation(recipe(),"lunch",context({promotions:[promo(true)]}))!;expect(ignored.score).toBe(base.score);expect(ignored.reasons.some(x=>x.includes("kampanj"))).toBe(false)});it("hemma, useFirst, favorit, protein och historik påverkar",()=>{const base=recipeToRecommendation(recipe(),"lunch",context())!,home=recipeToRecommendation(recipe(),"lunch",context({inventory:[inventory({normalizedName:"kycklingfilé"})]}))!,first=recipeToRecommendation(recipe({favorite:true,proteinGramsPerServing:60}),"lunch",context({inventory:[inventory({useFirst:true,normalizedName:"kycklingfilé"})]}))!,recent=recipeToRecommendation(recipe({lastCookedAt:now}),"lunch",context())!;expect(home.score).toBeGreaterThan(base.score);expect(first.score).toBeGreaterThan(home.score);expect(recent.score).toBeLessThan(base.score)});it("kalorier långt från mål får lägre score",()=>{expect(recipeToRecommendation(recipe({caloriesPerServing:620}),"lunch",context())!.score).toBeGreaterThan(recipeToRecommendation(recipe({caloriesPerServing:1800}),"lunch",context())!.score)})});
function recommendation(ingredients:WeeklyRecommendation["ingredients"],category:"lunch"|"dinner"="lunch"):WeeklyRecommendation{return{id:category,category,title:"R",sourceName:"Mitt recept",sourceUrl:"",sourceType:"personal",calories:600,protein:45,carbs:60,fat:18,servings:4,ingredients,primaryProtein:"Kyckling",cuisine:"",favorite:false,score:1,reasons:[]}}
describe("scaling and shopping",()=>{it("skalar fyra till fem portioner",()=>{expect(scaleIngredient("400",4,5)).toBe(500)});it("kombinerar före avdrag och köper bara resten",()=>{const list=buildShoppingList({lunch:recommendation([{name:"Ris",quantity:"300",unit:"g"}]),dinner:recommendation([{name:"Ris",quantity:"500",unit:"g"}],"dinner")},[inventory({displayName:"Ris",normalizedName:"ris",quantity:500})],[]);expect(list[0].quantity).toBe(500)});it("lager som överstiger behov ger ingen rad",()=>{expect(buildShoppingList({lunch:recommendation([{name:"Kycklingfilé",quantity:"800",unit:"g"}])},[inventory()],[])).toHaveLength(0)});it("okänd hemmamängd ger varning utan falskt avdrag",()=>{const row=buildShoppingList({lunch:recommendation([{name:"Vitlök",quantity:"2",unit:"st"}])},[inventory({displayName:"Vitlök",normalizedName:"vitlok",quantity:null,unit:null})],[])[0];expect(row.warning).toContain("kontrollera");expect(row.quantity).toBe(2.5)});it("markerar kampanj efter korrekt lageravdrag",()=>{const row=buildShoppingList({lunch:recommendation([{name:"Kycklingfilé",quantity:"1500",unit:"g"}])},[inventory()],[promo()])[0];expect(row.quantity).toBe(675);expect(row.promotion?.displayName).toBe("Kycklingfilé")})});
