import type { ExternalRecipeCandidate } from "../domain/externalRecipe";
import { candidateToRecipe } from "../domain/externalRecipe";
import { normalizeFoodName, type DietProfile, type InventoryItem, type StandardMeal } from "../domain/personalization";
import type { PromotionFlyer, PromotionItem } from "../domain/promotion";
import type { Recipe } from "../domain/recipe";
import { diverseTop, emptyDiagnostics, recipeToRecommendation, standardRecommendation, type FilterDiagnostics, type MacroFilters, type MealCategory, type ShoppingItem, type WeeklyPlan, type WeeklyRecommendation } from "../domain/weeklyPlan";

export function externalToRecipe(x: ExternalRecipeCandidate): Recipe { const draft = candidateToRecipe(x), now = x.discoveredAt; return { ...draft, id: x.id, createdAt: now, updatedAt: now, timesCooked: 0, lastCookedAt: undefined }; }
export interface RecommendationResult { recommendations: Record<MealCategory, WeeklyRecommendation[]>; diagnostics: Record<MealCategory, FilterDiagnostics>; totalCandidates: number }
export function buildRecommendationResult(input: { profile: DietProfile; breakfast: StandardMeal; snack: StandardMeal; recipes: Recipe[]; external?: ExternalRecipeCandidate[]; promotions: PromotionItem[]; inventory: InventoryItem[]; macroFilters: MacroFilters; excludedIds?:Set<string> }): RecommendationResult {
  const recipes = input.recipes, context = { dailyCalories: input.profile.dailyCalories, proteinPriority: input.profile.proteinPriority, promotions: input.promotions, inventory: input.inventory, macroFilters: input.macroFilters };
  const diagnostics = { breakfast: emptyDiagnostics(), lunch: emptyDiagnostics(), dinner: emptyDiagnostics(), snack: emptyDiagnostics() };
  const build = (category: MealCategory) => recipes.map(r => recipeToRecommendation(r, category, context, diagnostics[category])).filter((x): x is WeeklyRecommendation => !!x && !input.excludedIds?.has(x.id)).sort((a,b)=>b.score-a.score);
  return { recommendations: { breakfast: [...build("breakfast"), standardRecommendation(input.breakfast, "breakfast")], lunch: build("lunch"), dinner: build("dinner"), snack: [...build("snack"), standardRecommendation(input.snack, "snack")] }, diagnostics, totalCandidates: recipes.length };
}
export const buildRecommendations = (input: Parameters<typeof buildRecommendationResult>[0]) => buildRecommendationResult(input).recommendations;
export function scaleIngredient(quantity: string, fromServings: number | null, toServings: number) { const n = Number(quantity.replace(",", ".")); return Number.isFinite(n) && fromServings && fromServings > 0 ? Math.round(n * (toServings / fromServings) * 100) / 100 : null; }
export function buildShoppingList(selections: Partial<Record<MealCategory, WeeklyRecommendation>>, inventory: InventoryItem[], promotions: PromotionItem[]): ShoppingItem[] { const needs = new Map<string, { displayName: string; quantity: number | null; unit: string | null; unknown: boolean }>(); for (const [category, meal] of Object.entries(selections) as [MealCategory, WeeklyRecommendation][]) { if (!meal) continue; const target = category === "lunch" || category === "dinner" ? 5 : 5; for (const ingredient of meal.ingredients) { const key = normalizeFoodName(ingredient.name), scaled = scaleIngredient(ingredient.quantity, meal.servings, target), old = needs.get(key); if (old && scaled != null && old.quantity != null && old.unit === ingredient.unit) old.quantity += scaled; else if (!old) needs.set(key, { displayName: ingredient.name, quantity: scaled, unit: ingredient.unit || null, unknown: scaled == null }); else old.unknown = true; } } return [...needs.entries()].map(([normalizedName, need]) => { const home = inventory.find(x => normalizedName.includes(x.normalizedName) || x.normalizedName.includes(normalizedName)), promotion = promotions.find(x => !x.ignored && (normalizedName.includes(x.normalizedName) || x.normalizedName.includes(normalizedName))); let quantity = need.quantity, warning: string | undefined; if (home) { if (home.quantity == null) warning = "Finns hemma – kontrollera mängd"; else if (quantity != null && (!home.unit || !need.unit || home.unit === need.unit)) quantity = Math.max(0, quantity - home.quantity); } return { displayName: need.displayName, normalizedName, quantity, unit: need.unit, homeQuantity: home?.quantity ?? null, warning, promotion: promotion ? { displayName: promotion.displayName, price: promotion.price, priceType: promotion.priceType } : undefined }; }).filter(x => x.quantity !== 0 || x.warning); }
export function createWeeklyPlan(input: { profile: DietProfile; flyer?: PromotionFlyer; recommendations: Record<MealCategory, WeeklyRecommendation[]>; selections: Partial<Record<MealCategory, WeeklyRecommendation>>; inventory: InventoryItem[]; promotions: PromotionItem[]; macroFilters: MacroFilters }): WeeklyPlan { const now=new Date().toISOString(); return { id: crypto.randomUUID(), createdAt: now, updatedAt:now, dietPhaseSnapshot: input.profile.phase, calorieTargetSnapshot: input.profile.dailyCalories, macroFiltersSnapshot: input.macroFilters, activeFlyerId: input.flyer?.id, recommendations: input.recommendations, selections: input.selections, shoppingList: buildShoppingList(input.selections, input.inventory, input.promotions), status: "finalized" }; }
export function replaceWeeklySelection(plan:WeeklyPlan,category:MealCategory,replacement:WeeklyRecommendation,inventory:InventoryItem[],promotions:PromotionItem[]):WeeklyPlan{const selections={...plan.selections,[category]:replacement};return{...plan,updatedAt:new Date().toISOString(),selections,shoppingList:buildShoppingList(selections,inventory,promotions)}}
const section=(x:ShoppingItem)=>{const n=x.normalizedName;if(/kyck|kött|färs|lax|fisk|ägg|kvarg/.test(n))return"KÖTT & PROTEIN";if(/mjölk|grädde|yoghurt|ost|fraiche|smör/.test(n))return"MEJERI";if(/paprika|broccoli|lök|spenat|tomat|frukt|citron|äpple|banan/.test(n))return"FRUKT & GRÖNT";return"SKAFFERI"};
export function formatShoppingList(items:ShoppingItem[]){const groups=new Map<string,ShoppingItem[]>();for(const item of items){const key=section(item);groups.set(key,[...(groups.get(key)??[]),item])}const lines=["INKÖPSLISTA — MEAL PREP",""];for(const[key,values]of groups){lines.push(key,...values.map(x=>`☐ ${x.displayName} — ${x.quantity!=null?`${Math.round(x.quantity*100)/100} ${x.unit??""}`.trim():"Kontrollera"}`),"")}const campaigns=items.filter(x=>x.promotion);if(campaigns.length)lines.push("KAMPANJ",...campaigns.map(x=>`${x.displayName} — Willys${x.promotion?.price!=null?` ${x.promotion.price} kr`:""}`));return lines.join("\n").trim()}
