import{describe,expect,it}from"vitest";
import{EMPTY_MACRO_FILTERS,macroFailure,type MacroFilters,type WeeklyPlan,type WeeklyRecommendation}from"../domain/weeklyPlan";
import{buildRecommendationResult,buildShoppingList,formatShoppingList,replaceWeeklySelection}from"./generator";
import{emptyRecipe,type Recipe}from"../domain/recipe";
import{defaultBreakfast,defaultSnack}from"../domain/personalization";
const now=new Date().toISOString();
const rec=(id:string,category:"lunch"|"dinner",ingredient:string):WeeklyRecommendation=>({id,category,title:id,sourceName:"Mitt recept",sourceUrl:"",sourceType:"personal",calories:500,protein:45,carbs:50,fat:20,servings:5,ingredients:[{name:ingredient,quantity:"500",unit:"g"}],primaryProtein:id,cuisine:"",favorite:false,score:1,reasons:[]});
describe("Milestone 7.1 macro filters",()=>{it("excludes fat above maximum",()=>{const f=structuredClone(EMPTY_MACRO_FILTERS);f.fat.max=30;expect(macroFailure({calories:500,protein:50,carbs:40,fat:42},f)).toBe("fatMax")});it("excludes protein below minimum",()=>{const f=structuredClone(EMPTY_MACRO_FILTERS);f.protein.min=40;expect(macroFailure({calories:500,protein:39,carbs:40,fat:20},f)).toBe("proteinMin")});it("blank maximum does not filter fat",()=>{expect(macroFailure({calories:500,protein:39,carbs:40,fat:99},EMPTY_MACRO_FILTERS)).toBeNull()});it("passes all bounds and still rejects incomplete macros",()=>{const f:MacroFilters={calories:{min:450,max:700},protein:{min:40,max:null},carbs:{min:null,max:90},fat:{min:null,max:30}};expect(macroFailure({calories:600,protein:45,carbs:70,fat:20},f)).toBeNull();expect(macroFailure({calories:600,protein:45,carbs:null,fat:20},f)).toBe("incompleteMacros")})});
describe("Milestone 7.1 counts and editing",()=>{it("returns ten lunches when forty qualify",()=>{const recipes:Recipe[]=Array.from({length:40},(_,i)=>({...emptyRecipe(),id:`r${i}`,title:`Rätt ${i}`,sourceType:"personal" as const,sourceUrl:`https://example.com/${i}`,servings:4,mealTypes:["Lunch"],primaryProtein:`protein-${i}`,caloriesPerServing:500,proteinGramsPerServing:45,carbsGramsPerServing:50,fatGramsPerServing:20,nutritionComplete:true,favorite:false,timesCooked:0,ingredients:[],instructions:[],createdAt:now,updatedAt:now}));const result=buildRecommendationResult({profile:{phase:"maintenance",dailyCalories:2500,calorieFlexibility:"flexible",proteinPriority:"high"},breakfast:defaultBreakfast(),snack:defaultSnack(),recipes,external:[],promotions:[],inventory:[],macroFilters:EMPTY_MACRO_FILTERS});expect(result.recommendations.lunch).toHaveLength(10)});it("changes dinner only and recalculates shopping",()=>{const lunch=rec("lunch","lunch","Ris"),oldDinner=rec("old","dinner","Pasta"),newDinner=rec("new","dinner","Potatis"),selections={lunch,dinner:oldDinner};const plan={id:"p",createdAt:now,updatedAt:now,dietPhaseSnapshot:"maintenance",calorieTargetSnapshot:2500,macroFiltersSnapshot:EMPTY_MACRO_FILTERS,recommendations:{breakfast:[],lunch:[],dinner:[oldDinner,newDinner],snack:[]},selections,shoppingList:buildShoppingList(selections,[],[]),status:"finalized"}as WeeklyPlan;const changed=replaceWeeklySelection(plan,"dinner",newDinner,[],[]);expect(changed.selections.lunch).toBe(lunch);expect(changed.shoppingList.some(x=>x.normalizedName==="potatis")).toBe(true);expect(changed.shoppingList.some(x=>x.normalizedName==="pasta")).toBe(false)});it("copies complete categorized text",()=>{const items=buildShoppingList({lunch:{...rec("l","lunch","Kycklingfilé"),ingredients:[{name:"Kycklingfilé",quantity:"1000",unit:"g"},{name:"Ris",quantity:"400",unit:"g"}]}},[],[]),text=formatShoppingList(items);expect(text).toContain("INKÖPSLISTA — MEAL PREP");expect(text).toContain("☐ Kycklingfilé");expect(text).toContain("☐ Ris")})});
