import{describe,expect,it}from"vitest";
import{defaultBreakfast,defaultSnack,normalizeFoodName,type InventoryItem}from"../domain/personalization";
import{emptyPromotion,type PromotionItem}from"../domain/promotion";
import{emptyRecipe,type Recipe}from"../domain/recipe";
import{EMPTY_MACRO_FILTERS,emptyWeeklySelections,type MealCategory,type WeeklyPlan,type WeeklyRecommendation}from"../domain/weeklyPlan";
import{buildRecommendationResult,buildShoppingList,calculateNutritionSummary,calculateSelectionDailyAverage,formatShoppingList,groceryCategory,makeWeeklySelection,normalizeWeeklyPlan,removeWeeklySelection,updateWeeklySelection}from"./generator";
const now="2026-08-20T12:00:00.000Z",profile={phase:"maintenance"as const,dailyCalories:2500,calorieFlexibility:"flexible"as const,proteinPriority:"high"as const};
const promo=(id:string,name:string):PromotionItem=>({...emptyPromotion(),id,flyerId:"f",displayName:name,normalizedName:name.toLocaleLowerCase("sv"),ignored:false,createdAt:now,updatedAt:now});
const recipe=(id:string,ingredients:Array<[string,string,string]>,changes:Partial<Recipe>={}):Recipe=>({...emptyRecipe(),id,title:id,sourceType:"personal",originalServings:5,servings:5,mealTypes:["Lunch"],primaryProtein:id,favorite:false,timesCooked:0,createdAt:now,updatedAt:now,caloriesPerServing:600,proteinGramsPerServing:45,carbsGramsPerServing:55,fatGramsPerServing:20,ingredients:ingredients.map(([name,quantity,unit],index)=>({id:String(index),name,quantity,unit})),instructions:[],...changes});
const recommendation=(id:string,category:MealCategory,calories:number|null,ingredient="Ris",quantity="500",originalServings:number|null=5):WeeklyRecommendation=>({id,category,title:id,sourceName:"Mina recept",sourceUrl:"",sourceType:"personal",calories,protein:calories==null?null:40,carbs:calories==null?null:50,fat:calories==null?null:20,servings:originalServings,originalServings,ingredients:[{name:ingredient,quantity,unit:"g"}],primaryProtein:id,cuisine:"",favorite:false,score:1,campaignRelevance:0,reasons:[]});
const inventory=(name:string,quantity:number):InventoryItem=>({id:name,displayName:name,normalizedName:normalizeFoodName(name),quantity,unit:"g",location:"freezer",notes:"",useFirst:false,createdAt:now,updatedAt:now});

describe("campaign-first personal recipe order",()=>{it("sorterar tre meningsfulla träffar före en och noll",()=>{const recipes=[recipe("A",[["Kycklingfilé","1000","g"],["Paprika","2","st"],["Ris","500","g"]]),recipe("B",[["Kycklingfilé","200","g"]]),recipe("C",[["Pasta","400","g"]])],promotions=[promo("p1","Kycklingfilé"),promo("p2","Paprika"),promo("p3","Jasminris")],result=buildRecommendationResult({profile,breakfast:defaultBreakfast(),snack:defaultSnack(),recipes,promotions,inventory:[],macroFilters:EMPTY_MACRO_FILTERS});expect(result.recommendations.lunch.map(item=>item.id)).toEqual(["A","B","C"]);expect(result.recommendations.lunch[0].campaignMatches?.map(match=>match.ingredientName)).toEqual(["Kycklingfilé","Paprika","Ris"])});it("matchar inte kycklingfond mot kycklingfilé",()=>{const result=buildRecommendationResult({profile,breakfast:defaultBreakfast(),snack:defaultSnack(),recipes:[recipe("Fond",[["Kycklingfond","2","msk"]])],promotions:[promo("p","Kycklingfilé")],inventory:[],macroFilters:EMPTY_MACRO_FILTERS});expect(result.recommendations.lunch[0].campaignMatches).toHaveLength(0)})});

describe("multiple recipes and independent portions",()=>{it("behåller flera val och kombinerar skalade behov",()=>{const selections=emptyWeeklySelections(),cajun=recommendation("Cajun","lunch",650,"Kycklingfilé","1200",6),salad=recommendation("Caesar","lunch",500,"Kycklingfilé","800",4),lasagne=recommendation("Lasagne","dinner",700,"Pasta","1000",5),tacos=recommendation("Tacos","dinner",600,"Kycklingfilé","500",5);selections.lunch=[makeWeeklySelection(cajun,3),makeWeeklySelection(salad,2)];selections.dinner=[makeWeeklySelection(lasagne,4),makeWeeklySelection(tacos,2,"Helg")];const list=buildShoppingList(selections,[inventory("Kycklingfilé",700)],[]),chicken=list.find(item=>item.normalizedName==="kycklingfile")!;expect(selections.lunch).toHaveLength(2);expect(selections.dinner.map(item=>item.desiredServings)).toEqual([4,2]);expect(chicken.requiredQuantity).toBe(1200);expect(chicken.buyQuantity).toBe(500);const summary=calculateNutritionSummary(selections,5,2500);expect(summary.plannedDaily).toBeNull();expect(summary.categories.lunch.averagePerServing?.calories).toBe(590)});it("tar bort endast ett val och portionsändring räknar om",()=>{const selections=emptyWeeklySelections(),a=makeWeeklySelection(recommendation("A","lunch",600),3),b=makeWeeklySelection(recommendation("B","lunch",500),2);selections.lunch=[a,b];const plan={id:"p",createdAt:now,updatedAt:now,dietPhaseSnapshot:"maintenance",calorieTargetSnapshot:2500,macroFiltersSnapshot:EMPTY_MACRO_FILTERS,plannedDays:5,recommendations:{breakfast:[],lunch:[a.recipe,b.recipe],dinner:[],snack:[]},selections,shoppingList:buildShoppingList(selections,[],[]),status:"finalized"}as WeeklyPlan,changed=updateWeeklySelection(plan,"lunch",a.id,{desiredServings:4},[],[]),removed=removeWeeklySelection(changed,"lunch",b.id,[],[]);expect(changed.selections.lunch.find(item=>item.id===a.id)?.desiredServings).toBe(4);expect(removed.selections.lunch.map(item=>item.recipe.id)).toEqual(["A"]);expect(removed.shoppingList[0].requiredQuantity).toBe(400)})});

describe("nutrition transparency",()=>{it("skiljer per portion, batch och exakt dagsvärde",()=>{const selections=emptyWeeklySelections(),calories:Record<MealCategory,number>={breakfast:500,lunch:600,dinner:700,snack:400};for(const category of Object.keys(calories)as MealCategory[])selections[category]=[makeWeeklySelection(recommendation(category,category,calories[category]),5)];const summary=calculateNutritionSummary(selections,5,2500);expect(summary.plannedDaily?.calories).toBe(2200);expect(summary.differenceCalories).toBe(300);expect(summary.categories.lunch.batchTotals?.calories).toBe(3000);expect(selections.lunch[0].recipe.calories).toBe(600)});it("fabricerar inte totaler när ett valt recept saknar makron",()=>{const selections=emptyWeeklySelections();for(const category of["breakfast","lunch","dinner","snack"]as MealCategory[])selections[category]=[makeWeeklySelection(recommendation(category,category,category==="dinner"?null:500),5)];const summary=calculateNutritionSummary(selections,5,2500);expect(summary.plannedDaily).toBeNull();expect(summary.missingNutritionCount).toBe(1)})});

describe("live daily macro average",()=>{it("uses selected portions divided by planning days and recalculates after another choice",()=>{const selections=emptyWeeklySelections(),breakfast={...recommendation("Frukost","breakfast",350),protein:30,carbs:40,fat:8},lunch={...recommendation("Lunch","lunch",600),protein:45,carbs:60,fat:20};selections.breakfast=[makeWeeklySelection(breakfast,5)];selections.lunch=[makeWeeklySelection(lunch,5)];expect(calculateSelectionDailyAverage(selections,5).totals).toEqual({calories:950,protein:75,carbs:100,fat:28});selections.snack=[makeWeeklySelection({...recommendation("Snack","snack",100),protein:10,carbs:5,fat:3},5)];expect(calculateSelectionDailyAverage(selections,5).totals).toEqual({calories:1050,protein:85,carbs:105,fat:31})})});

describe("simple categorized shopping copy",()=>{it("uses grocery categories, practical units and a plain check section",()=>{const item=(displayName:string,buyQuantity:number|null,unit:string|null)=>({displayName,normalizedName:normalizeFoodName(displayName),quantity:buyQuantity,buyQuantity,requiredQuantity:buyQuantity,unit,homeQuantity:0});const text=formatShoppingList([item("gurka",2,"st"),item("potatis",2200,"g"),item("kycklingfilé",1200,"g"),item("salt",null,null)]);expect(groceryCategory(item("rödlök",2,"st"))).toBe("FRUKT & GRÖNT");expect(text).toContain("Gurka — 2 st");expect(text).toContain("Potatis — 2,2 kg");expect(text).toContain("Kycklingfilé — 1,2 kg");expect(text).toContain("KONTROLLERA\nSalt");expect(text).not.toMatch(/Behövs|Hemma 0|Köp Kontrollera/)})});

describe("safe legacy migration",()=>{it("migrerar gammalt ensamt val till lista utan dataförlust",()=>{const old=recommendation("Legacy","lunch",600),plan=normalizeWeeklyPlan({id:"old",createdAt:now,updatedAt:now,dietPhaseSnapshot:"maintenance",calorieTargetSnapshot:2500,macroFiltersSnapshot:EMPTY_MACRO_FILTERS,recommendations:{breakfast:[],lunch:[old],dinner:[],snack:[]},selections:{lunch:old},shoppingList:[],status:"finalized"});expect(plan.plannedDays).toBe(5);expect(plan.selections.lunch).toHaveLength(1);expect(plan.selections.lunch[0]).toMatchObject({desiredServings:5,recipe:{id:"Legacy"}})})});
