import { useEffect, useState } from "react";
import type { InventoryItem, StandardMeal, DietProfile } from "../domain/personalization";
import type { PromotionFlyer, PromotionItem } from "../domain/promotion";
import type { Recipe } from "../domain/recipe";
import { EMPTY_MACRO_FILTERS, type FilterDiagnostics, type MacroFilters, type MacroKey, type MealCategory, type WeeklyPlan, type WeeklyRecommendation } from "../domain/weeklyPlan";
import { getActiveDietProfile, getDefaultBreakfast, getDefaultSnack, getInventoryItems, getMacroFilters, saveMacroFilters } from "../storage/personalization";
import { getActivePromotionWeek } from "../storage/promotions";
import { listRecipes } from "../storage/recipes";
import { getLatestWeeklyPlan, saveWeeklyPlan } from "../storage/weeklyPlans";
import { buildRecommendationResult, createWeeklyPlan, formatShoppingList, replaceWeeklySelection } from "../weekly/generator";
import { WeekPromotions } from "./WeekPromotions";

type Inputs={profile:DietProfile;breakfast:StandardMeal;snack:StandardMeal;inventory:InventoryItem[];recipes:Recipe[];promotions:PromotionItem[];flyer?:PromotionFlyer;macroFilters:MacroFilters};
const categories:MealCategory[]=["breakfast","lunch","dinner","snack"];
const labels:Record<MealCategory,string>={breakfast:"Frukost",lunch:"Lunch",dinner:"Middag",snack:"Mellanmål"};

export function WeeklyGenerator(){
 const[inputs,setInputs]=useState<Inputs>(),[recommendations,setRecommendations]=useState<Record<MealCategory,WeeklyRecommendation[]>>(),[diagnostics,setDiagnostics]=useState<Record<MealCategory,FilterDiagnostics>>(),[selections,setSelections]=useState<Partial<Record<MealCategory,WeeklyRecommendation>>>({}),[busy,setBusy]=useState(false),[stage,setStage]=useState(""),[notice,setNotice]=useState(""),[plan,setPlan]=useState<WeeklyPlan>(),[editCategory,setEditCategory]=useState<MealCategory>(),[copied,setCopied]=useState(false);
 async function load(){const[profile,breakfast,snack,inventory,recipes,promo,latest,macroFilters]=await Promise.all([getActiveDietProfile(),getDefaultBreakfast(),getDefaultSnack(),getInventoryItems(),listRecipes(),getActivePromotionWeek(),getLatestWeeklyPlan(),getMacroFilters()]);const data={profile,breakfast,snack,inventory,recipes,promotions:promo?.items.filter(x=>!x.ignored)??[],flyer:promo?.flyer,macroFilters};setInputs(data);if(latest?.status==="finalized")setPlan({...latest,macroFiltersSnapshot:latest.macroFiltersSnapshot??macroFilters,updatedAt:latest.updatedAt??latest.createdAt})}
 useEffect(()=>{void load()},[]);
 async function updateFilters(value:MacroFilters){if(!inputs)return;await saveMacroFilters(value);setInputs({...inputs,macroFilters:value});setRecommendations(undefined);setPlan(undefined)}
 async function generate(){if(!inputs)return;setBusy(true);setNotice("");setStage("Matchar kampanjer mot Mina recept…");const result=buildRecommendationResult(inputs);setRecommendations(result.recommendations);setDiagnostics(result.diagnostics);setSelections({});setPlan(undefined);setBusy(false);if(!inputs.recipes.length)setNotice("Lägg till recept i Mina recept för att få personliga kampanjförslag.")
 }
 async function finalize(){if(!inputs||!recommendations)return;const value=createWeeklyPlan({...inputs,recommendations,selections});await saveWeeklyPlan(value);setPlan(value)}
 async function confirmReplacement(x:WeeklyRecommendation){if(!inputs||!plan||!editCategory)return;const value=replaceWeeklySelection(plan,editCategory,x,inputs.inventory,inputs.promotions);await saveWeeklyPlan(value);setPlan(value);setEditCategory(undefined)}
 async function refreshShopping(){if(!inputs||!plan)return;const value={...plan,updatedAt:new Date().toISOString(),shoppingList:replaceWeeklySelection(plan,"breakfast",plan.selections.breakfast!,inputs.inventory,inputs.promotions).shoppingList};await saveWeeklyPlan(value);setPlan(value)}
 async function copyList(){if(!plan)return;const text=formatShoppingList(plan.shoppingList);try{await navigator.clipboard.writeText(text)}catch{const el=document.createElement("textarea");el.value=text;el.style.position="fixed";el.style.opacity="0";document.body.append(el);el.select();document.execCommand("copy");el.remove()}setCopied(true);setTimeout(()=>setCopied(false),2500)}
 if(!inputs)return<main className="page"><p>Laddar veckodata…</p></main>;
 return<><main className="page weekly-page"><p className="eyebrow">Din matvecka</p><h1>Vecka</h1>
  {!recommendations&&!plan?<section className="week-summary"><h2>Skapa veckans mat</h2><dl><div><dt>Kostfas</dt><dd>{inputs.profile.phase==="cut"?"DEFF":inputs.profile.phase==="bulk"?"BULK":"UNDERHÅLL"}</dd></div><div><dt>Kalorimål</dt><dd>{inputs.profile.dailyCalories??"Ej angivet"} kcal/dag</dd></div><div><dt>Willys</dt><dd>{inputs.promotions.length} aktiva kampanjer</dd></div><div><dt>Hemma</dt><dd>{inputs.inventory.length} ingredienser</dd></div></dl><MacroFilterForm value={inputs.macroFilters} onSave={updateFilters}/>{!inputs.flyer?<p className="week-notice">Inget aktivt reklamblad – rekommendationerna baseras på dina recept, hemma-varor och kostprofil.</p>:null}<button className="primary" disabled={busy} onClick={()=>void generate()}>{busy?stage:"GENERERA FÖRSLAG"}</button></section>:null}
  {notice?<p className="week-notice">{notice}</p>:null}
  {recommendations&&!plan?<><ActiveFilters filters={inputs.macroFilters}/>{categories.map(category=><MealOptions key={category} category={category} items={recommendations[category]} selected={selections[category]?.id} diagnostics={diagnostics?.[category]} onSelect={x=>setSelections({...selections,[category]:x})}/>)}<button className="primary create-week" disabled={categories.some(c=>!selections[c])} onClick={()=>void finalize()}>SKAPA MIN VECKA</button></>:null}
  {plan?<PlanView plan={plan} editCategory={editCategory} onEdit={setEditCategory} onCancel={()=>setEditCategory(undefined)} onConfirm={x=>void confirmReplacement(x)} onCopy={()=>void copyList()} onRefresh={()=>void refreshShopping()} onNew={()=>{setPlan(undefined);setRecommendations(undefined);setSelections({})}}/>:null}
  {copied?<div className="copy-toast" role="status">✓ Inköpslistan kopierad</div>:null}
 </main>{!recommendations&&!plan?<WeekPromotions/>:null}</>
}

function MacroFilterForm({value,onSave}:{value:MacroFilters;onSave:(x:MacroFilters)=>Promise<void>}){const[draft,setDraft]=useState(value);const names:Record<MacroKey,string>={calories:"Kalorier (kcal)",protein:"Protein (g)",carbs:"Kolhydrater (g)",fat:"Fett (g)"};const change=(key:MacroKey,bound:"min"|"max",raw:string)=>setDraft({...draft,[key]:{...draft[key],[bound]:raw===""?null:Math.max(0,Number(raw))}});return<details className="macro-filter"><summary>Makrofilter</summary><p>Hårda gränser per portion. Tomt fält betyder ingen gräns.</p>{(Object.keys(names)as MacroKey[]).map(key=><div className="macro-filter-row" key={key}><b>{names[key]}</b><label>Min<input type="number" min="0" inputMode="decimal" value={draft[key].min??""} onChange={e=>change(key,"min",e.target.value)}/></label><label>Max<input type="number" min="0" inputMode="decimal" value={draft[key].max??""} onChange={e=>change(key,"max",e.target.value)}/></label></div>)}<button className="secondary" onClick={()=>void onSave(draft)}>SPARA MAKROFILTER</button></details>}
function ActiveFilters({filters}:{filters:MacroFilters}){const names:Record<MacroKey,string>={calories:"kcal",protein:"g protein",carbs:"g kolhydrater",fat:"g fett"};const values=(Object.keys(names)as MacroKey[]).flatMap(k=>[filters[k].min!=null?`≥ ${filters[k].min} ${names[k]}`:"",filters[k].max!=null?`≤ ${filters[k].max} ${names[k]}`:""]).filter(Boolean);return values.length?<p className="active-filters"><b>Aktiva hårda filter:</b> {values.join(" · ")}</p>:null}
function MealOptions({category,items,selected,onSelect}:{category:MealCategory;items:WeeklyRecommendation[];selected?:string;onSelect:(x:WeeklyRecommendation)=>void;diagnostics?:FilterDiagnostics}){const campaign=items.filter(x=>x.campaignMatches?.length),rest=items.filter(x=>!x.campaignMatches?.length);return<section className="meal-options"><h2>{labels[category]}</h2>{campaign.length?<><h3>Recept som passar veckans kampanjer</h3>{campaign.map(x=><RecommendationCard key={`${x.id}-${x.category}`} item={x} selected={selected===x.id} onSelect={()=>onSelect(x)}/>)}</>:null}<h3>Alla mina recept</h3>{rest.length?rest.map(x=><RecommendationCard key={`${x.id}-${x.category}`} item={x} selected={selected===x.id} onSelect={()=>onSelect(x)}/>):<p className="week-notice">Inga fler personliga recept är märkta som {labels[category].toLowerCase()}.</p>}</section>}
function RecommendationCard({item:x,selected,onSelect,confirm=false}:{item:WeeklyRecommendation;selected?:boolean;onSelect:()=>void;confirm?:boolean}){return<article className={`recommendation-card ${selected?"selected":""}`}>{x.standard?<b>⭐ DIN STANDARD</b>:null}<span className="recommendation-title">{x.title}</span><small>{x.sourceName}</small>{x.campaignMatches?.length?<p className="campaign-count">🔥 {x.campaignMatches.length} kampanjvaror</p>:null}{x.campaignMatches?.length?<div className="campaign-ingredients">{x.campaignMatches.map(m=><span key={m.promotionId}>{m.promotionName}</span>)}</div>:null}{x.calories!=null?<div className="recommendation-macros"><span>🔥 {x.calories} kcal</span><span>💪 {x.protein} g</span><span>🍚 {x.carbs} g</span><span>🥑 {x.fat} g</span></div>:<p>Makron saknas – receptet kan fortfarande väljas.</p>}<ul>{x.reasons.filter(r=>!r.startsWith("🔥")).map(r=><li key={r}>{r}</li>)}</ul><button className="select-recommendation" onClick={onSelect}>{confirm?"BEKRÄFTA BYTE":selected?"✓ VALD":"VÄLJ"}</button></article>}
function PlanView({plan,editCategory,onEdit,onCancel,onConfirm,onCopy,onRefresh,onNew}:{plan:WeeklyPlan;editCategory?:MealCategory;onEdit:(x:MealCategory)=>void;onCancel:()=>void;onConfirm:(x:WeeklyRecommendation)=>void;onCopy:()=>void;onRefresh:()=>void;onNew:()=>void}){const selected=Object.values(plan.selections).filter(Boolean)as WeeklyRecommendation[],known=selected.filter(x=>x.calories!=null),totals=known.reduce((a,x)=>({calories:a.calories+x.calories!,protein:a.protein+x.protein!,carbs:a.carbs+x.carbs!,fat:a.fat+x.fat!}),{calories:0,protein:0,carbs:0,fat:0});return<section className="final-week"><h2>Min vecka</h2>{known.length?<div className="week-macro-total"><b>Planerad dagsöversikt</b><span>{Math.round(totals.calories)} kcal</span><span>{Math.round(totals.protein)} g protein</span><span>{Math.round(totals.carbs)} g kolhydrater</span><span>{Math.round(totals.fat)} g fett</span></div>:null}{categories.map(key=>{const x=plan.selections[key];if(!x)return null;return<article key={key}><b>{labels[key]}</b><span>{x.title}</span>{x.calories!=null?<small>{x.calories} kcal · {x.protein} P · {x.carbs} K · {x.fat} F</small>:null}{key==="lunch"||key==="dinner"?<small>5 portioner</small>:null}<button className="small-action" onClick={()=>onEdit(key)}>ÄNDRA</button></article>})}{editCategory?<section className="edit-meal"><div className="edit-heading"><h3>Byt {labels[editCategory].toLowerCase()}</h3><button onClick={onCancel}>Avbryt</button></div><p>Ditt nuvarande val behålls tills du bekräftar ett byte.</p>{plan.recommendations[editCategory].filter(x=>x.id!==plan.selections[editCategory]?.id).map(x=><RecommendationCard key={x.id} item={x} confirm onSelect={()=>onConfirm(x)}/>)}</section>:null}<h2>Inköpslista</h2><div className="shopping-actions"><button className="primary" onClick={onCopy}>KOPIERA INKÖPSLISTA</button><button className="secondary" onClick={onRefresh}>RÄKNA OM MOT HEMMA</button></div>{plan.shoppingList.length?<ul>{plan.shoppingList.map(x=><li key={`${x.normalizedName}-${x.unit}`}><span><b>{x.displayName}</b>{x.warning?<small>⚠ {x.warning}</small>:null}{x.promotion?<small>🔥 Kampanj hos Willys: {x.promotion.price??""}</small>:null}</span><strong>{x.quantity!=null?`${Math.round(x.quantity*100)/100} ${x.unit??""}`:"Kontrollera"}</strong></li>)}</ul>:<p>Du verkar redan ha allt hemma.</p>}<button className="secondary" onClick={onNew}>SKAPA NY VECKA / ÄNDRA FILTER</button></section>}
