import { useEffect,useRef,useState } from "react";
import { FileUp,Plus,Tag,Trash2 } from "lucide-react";
import { categoryLabels,emptyPromotion,priceTypeLabels,promotionCategories,priceTypes,type PromotionDraft,type PromotionFlyer,type PromotionItem } from "../domain/promotion";
import { analyzeFlyer,FlyerAnalysisError,fingerprintFile } from "../promotion/flyerAnalyzer";
import { activatePromotionFlyer,deletePromotionFlyer,findFlyerByFingerprint,getActivePromotionWeek,getActiveFlyerId,listPromotionFlyers,savePromotionWeek } from "../storage/promotions";
type ReviewItem=PromotionDraft&{id?:string};
const messages=["Förbereder reklamblad…","Läser kampanjer…","Identifierar priser och produkter…","Sammanställer veckans erbjudanden…"];
export function WeekPromotions({onChanged}:{onChanged?:()=>void|Promise<void>}={}){
 const input=useRef<HTMLInputElement>(null);const [active,setActive]=useState<{flyer:PromotionFlyer;items:PromotionItem[]}|undefined>();const [history,setHistory]=useState<PromotionFlyer[]>([]);const [review,setReview]=useState<{flyer:Omit<PromotionFlyer,"promotionItemIds">;items:ReviewItem[]}|null>(null);const [busy,setBusy]=useState(false);const [actionBusy,setActionBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [status,setStatus]=useState("");const [show,setShow]=useState(false);
 async function refresh(){const[nextActive,nextHistory]=await Promise.all([getActivePromotionWeek(),listPromotionFlyers()]);setActive(nextActive);setHistory(nextHistory)}useEffect(()=>{void refresh()},[]);
 async function select(file?:File){if(!file)return;setError("");setBusy(true);let timer:number|undefined;try{const fingerprint=await fingerprintFile(file);const duplicate=await findFlyerByFingerprint(fingerprint);if(duplicate&&!confirm("Det här reklambladet verkar redan vara analyserat. Vill du analysera det igen?"))return;let step=0;setMessage(messages[0]);timer=window.setInterval(()=>setMessage(messages[Math.min(++step,messages.length-1)]),1800);const result=await analyzeFlyer(file);if(!result.promotions.length)throw new FlyerAnalysisError("no_promotions");setReview({flyer:{id:crypto.randomUUID(),store:"Willys",fileName:file.name,fingerprint,importedAt:new Date().toISOString(),validFrom:result.validFrom,validTo:result.validTo,numberOfPages:result.numberOfPages,analysisVersion:"flyer-v1",provider:"OpenAI",status:"review"},items:result.promotions});}catch(e){if(e instanceof FlyerAnalysisError)setError(errorText(e.code));else setError("Vi kunde inte läsa reklambladet.")}finally{if(timer)clearInterval(timer);setBusy(false);setMessage("");if(input.current)input.current.value=""}}
 async function changed(text:string){await refresh();await onChanged?.();setStatus(text)}
 async function activate(flyer:PromotionFlyer){setActionBusy(true);setError("");try{await activatePromotionFlyer(flyer.id);setShow(false);await changed("Reklambladet är nu aktivt.")}catch{setError("Reklambladet kunde inte aktiveras. Försök igen.")}finally{setActionBusy(false)}}
 async function removeFlyer(flyer:PromotionFlyer){const isActive=flyer.id===await getActiveFlyerId();if(isActive&&!confirm("Det här är ditt aktiva reklamblad. Vill du radera det?"))return;if(!isActive&&!confirm(`Radera ${flyer.fileName}?`))return;setActionBusy(true);setError("");try{await deletePromotionFlyer(flyer.id);setShow(false);await changed("Reklambladet är raderat.")}catch{setError("Reklambladet kunde inte raderas. Försök igen.")}finally{setActionBusy(false)}}
 async function save(){if(!review)return;if(review.items.some(x=>!x.displayName.trim())){setError("Alla kampanjer behöver ett produktnamn.");return}setActionBusy(true);setError("");try{await savePromotionWeek({flyer:{...review.flyer,status:"confirmed"},items:review.items});setReview(null);setShow(true);await changed("Det nya reklambladet är sparat och aktivt.")}catch{setError("Reklambladet kunde inte sparas. Försök igen.")}finally{setActionBusy(false)}}
 if(review)return <PromotionReview items={review.items} setItems={items=>setReview({...review,items})} onSave={()=>void save()} onCancel={()=>setReview(null)} error={error}/>;
 return <main className="page week-page"><p className="eyebrow">Din matvecka</p><h1>Vecka</h1>
  <section className="promotion-hero"><span className="promo-icon"><Tag/></span><div><h2>Veckans Willys-kampanjer</h2><p>Ladda upp reklambladet som PDF. AI hjälper dig hitta produkter och priser, sedan granskar du innan de sparas lokalt.</p></div>
  <button className="primary" disabled={busy||actionBusy} onClick={()=>input.current?.click()}><FileUp/>{busy?message:"Ladda upp reklamblad"}</button><input ref={input} className="file-input" type="file" accept="application/pdf,.pdf" onChange={e=>void select(e.target.files?.[0])}/>{error?<p className="form-error" role="alert">{error}</p>:null}{status?<p className="status" role="status">{status}</p>:null}<small>Ny analys kräver internet. Sparade kampanjer fungerar offline.</small></section>
  {active?<section className="active-week"><p className="eyebrow">Aktiv kampanjvecka</p><h2>Willys</h2><p>{dateRange(active.flyer)} · {active.items.filter(x=>!x.ignored).length} kampanjer</p><button className="secondary" onClick={()=>setShow(!show)}>Visa kampanjer</button></section>:null}
  {show&&active?<PromotionList items={active.items}/>:null}
  {history.length?<section className="flyer-history"><h2>Reklamblad</h2>{history.map(f=><article className="flyer-row" key={f.id}><span>{f.id===active?.flyer.id?<b>AKTIVT</b>:<small>TIDIGARE</small>}<strong>{flyerName(f)}</strong>{flyerName(f)!==f.fileName?<small>{f.fileName}</small>:null}<small>{dateRange(f)} · {f.promotionItemIds?.length??0} kampanjer</small></span><div>{f.id!==active?.flyer.id?<button disabled={actionBusy} onClick={()=>void activate(f)}>Aktivera</button>:null}<button className="delete" disabled={actionBusy} onClick={()=>void removeFlyer(f)}>Radera</button></div></article>)}</section>:null}
 </main>
}
function PromotionReview({items,setItems,onSave,onCancel,error}:{items:ReviewItem[];setItems:(x:ReviewItem[])=>void;onSave:()=>void;onCancel:()=>void;error:string}){const change=(i:number,patch:Partial<ReviewItem>)=>setItems(items.map((x,n)=>n===i?{...x,...patch}:x));return <main className="page review-promotions"><p className="eyebrow">Granska import</p><h1>Veckans kampanjer</h1><p>Kontrollera osäkra uppgifter. Du kan rätta eller ignorera varje erbjudande.</p>{items.map((item,i)=><article className={item.ignored?"promotion-edit ignored":"promotion-edit"} key={item.id??i}><div className="promo-heading"><b>{i+1}. {item.displayName||"Ny kampanj"}</b>{item.confidence<.75||item.warnings.length?<span>Kontrollera</span>:null}</div><label>Produkt<input value={item.displayName} onChange={e=>change(i,{displayName:e.target.value,normalizedName:e.target.value.toLocaleLowerCase("sv-SE")})}/></label><div className="field-grid"><label>Pris<input type="number" inputMode="decimal" value={item.price??""} onChange={e=>change(i,{price:e.target.value===""?null:Number(e.target.value)})}/></label><label>Enhet<input value={item.unit??""} onChange={e=>change(i,{unit:e.target.value||undefined})}/></label></div><div className="field-grid"><label>Typ<select value={item.priceType} onChange={e=>change(i,{priceType:e.target.value as any})}>{priceTypes.map(x=><option value={x} key={x}>{priceTypeLabels[x]}</option>)}</select></label><label>Kategori<select value={item.category} onChange={e=>change(i,{category:e.target.value as any})}>{promotionCategories.map(x=><option value={x} key={x}>{categoryLabels[x]}</option>)}</select></label></div><label>Villkor<input value={item.conditions??""} onChange={e=>change(i,{conditions:e.target.value||undefined})}/></label>{item.warnings.map((w,n)=><p className="warning" key={n}>{w}</p>)}<div className="promo-actions"><button onClick={()=>change(i,{ignored:!item.ignored})}>{item.ignored?"Återställ":"Ignorera"}</button><button className="delete" aria-label={`Ta bort ${item.displayName}`} onClick={()=>setItems(items.filter((_,n)=>n!==i))}><Trash2/> Ta bort</button></div></article>)}<button className="add-row" onClick={()=>setItems([...items,emptyPromotion()])}><Plus/> Lägg till kampanj manuellt</button>{error?<p className="form-error">{error}</p>:null}<div className="review-save"><button className="secondary" onClick={onCancel}>Avbryt</button><button className="primary" onClick={onSave}>Spara veckans kampanjer</button></div></main>}
function PromotionList({items}:{items:PromotionItem[]}){return <section className="promotion-list">{items.map(x=><article className={x.ignored?"ignored":""} key={x.id}><div><h3>{x.displayName}</h3><p>{categoryLabels[x.category]}{x.conditions?` · ${x.conditions}`:""}</p></div><strong>{formatPrice(x)}</strong>{x.ignored?<span>Ignorerad</span>:null}</article>)}</section>}
const formatPrice=(x:PromotionItem)=>x.multibuy?`${x.multibuy.quantity} för ${x.multibuy.totalPrice.toLocaleString("sv-SE")} kr`:x.price==null?"Pris osäkert":`${x.price.toLocaleString("sv-SE")} kr${x.priceType==="perKg"?"/kg":x.priceType==="perUnit"?"/st":""}`;
const dateRange=(f:PromotionFlyer)=>f.validFrom&&f.validTo?`${f.validFrom}–${f.validTo}`:new Date(f.importedAt).toLocaleDateString("sv-SE");
const flyerName=(f:PromotionFlyer)=>{if(f.validFrom){const d=new Date(`${f.validFrom}T12:00:00`),start=new Date(d.getFullYear(),0,1),week=Math.ceil((((d.getTime()-start.getTime())/86400000)+start.getDay()+1)/7);return`Willys vecka ${week}`}return f.fileName||"Willys reklamblad"};
function errorText(code:string){if(code==="invalid_pdf")return"Välj ett giltigt PDF-reklamblad på högst 20 MB.";if(code==="no_promotions")return"Inga tydliga kampanjer hittades.";if(code==="rate_limit")return"AI-tjänsten är tillfälligt upptagen. Försök igen senare.";if(code==="spend_limit")return"Projektets kostnadsgräns är nådd.";if(code==="analysis_timeout")return"Reklambladet tog för lång tid att tolka. Försök igen — större reklamblad kan behöva lite mer tid.";if(code==="authentication_failed")return"AI-tjänstens serveranslutning behöver återställas.";if(code==="worker_unavailable")return"AI-tolkningen kunde inte slutföras. Kontrollera internetanslutningen.";return"AI-tolkningen kunde inte slutföras. Försök igen."}
