import { getDB } from './db'
import type { Ingredient,InstructionStep,Recipe,RecipeDraft } from '../domain/recipe'
type StoredRecipe=Omit<Recipe,'ingredients'|'instructions'>
type IngredientRecord=Ingredient&{recipeId:string}
type StepRecord=InstructionStep&{recipeId:string}
const recipeFields=(recipe:Recipe&{importWarnings?:string[]}):StoredRecipe=>{const {ingredients:_,instructions:__,importWarnings:___,...base}=recipe;return base}
export async function listRecipes():Promise<Recipe[]>{const db=await getDB();const [bases,ingredients,steps]=await Promise.all([db.getAll('recipes') as Promise<StoredRecipe[]>,db.getAll('recipeIngredients') as Promise<IngredientRecord[]>,db.getAll('instructionSteps') as Promise<StepRecord[]>]);const ingredientMap=new Map<string,Ingredient[]>(),stepMap=new Map<string,InstructionStep[]>();for(const {recipeId,...item}of ingredients)ingredientMap.set(recipeId,[...(ingredientMap.get(recipeId)??[]),item]);for(const {recipeId,...item}of steps)stepMap.set(recipeId,[...(stepMap.get(recipeId)??[]),item]);return bases.map(base=>({...base,originalServings:base.originalServings??base.servings??null,ingredients:ingredientMap.get(base.id)??[],instructions:(stepMap.get(base.id)??[]).sort((a,b)=>a.order-b.order)}))}
export async function getRecipe(id:string){return(await listRecipes()).find(recipe=>recipe.id===id)}
export async function saveRecipe(draft:RecipeDraft):Promise<Recipe>{const db=await getDB(),now=new Date().toISOString(),id=draft.id??crypto.randomUUID(),originalServings=draft.originalServings??draft.servings??null;const recipe:Recipe={...draft,id,servings:originalServings??undefined,originalServings,createdAt:draft.createdAt??now,updatedAt:now,timesCooked:draft.timesCooked??0,ingredients:draft.ingredients.filter(i=>i.name.trim()).map(i=>({...i,id:i.id||crypto.randomUUID()})),instructions:draft.instructions.filter(s=>s.text.trim()).map((s,index)=>({...s,id:s.id||crypto.randomUUID(),order:index+1}))};const tx=db.transaction(['recipes','recipeIngredients','instructionSteps'],'readwrite');await tx.objectStore('recipes').put(recipeFields(recipe),id);const oldIngredients=await tx.objectStore('recipeIngredients').getAllKeys();for(const key of oldIngredients)if(String(key).startsWith(`${id}:`))await tx.objectStore('recipeIngredients').delete(key);const oldSteps=await tx.objectStore('instructionSteps').getAllKeys();for(const key of oldSteps)if(String(key).startsWith(`${id}:`))await tx.objectStore('instructionSteps').delete(key);for(const item of recipe.ingredients)await tx.objectStore('recipeIngredients').put({...item,recipeId:id},`${id}:${item.id}`);for(const item of recipe.instructions)await tx.objectStore('instructionSteps').put({...item,recipeId:id},`${id}:${item.id}`);await tx.done;return recipe}
export async function deleteRecipe(id:string){const db=await getDB();const tx=db.transaction(['recipes','recipeIngredients','instructionSteps'],'readwrite');await tx.objectStore('recipes').delete(id);for(const key of await tx.objectStore('recipeIngredients').getAllKeys())if(String(key).startsWith(`${id}:`))await tx.objectStore('recipeIngredients').delete(key);for(const key of await tx.objectStore('instructionSteps').getAllKeys())if(String(key).startsWith(`${id}:`))await tx.objectStore('instructionSteps').delete(key);await tx.done}
export async function updateRecipe(id:string,changes:Partial<Recipe>){const recipe=await getRecipe(id);if(!recipe)throw new Error('Receptet finns inte.');return saveRecipe({...recipe,...changes,id})}
export async function toggleFavorite(id:string){const recipe=await getRecipe(id);if(!recipe)throw new Error('Receptet finns inte.');return updateRecipe(id,{favorite:!recipe.favorite})}
export async function markCooked(id:string){const recipe=await getRecipe(id);if(!recipe)throw new Error('Receptet finns inte.');return updateRecipe(id,{timesCooked:recipe.timesCooked+1,lastCookedAt:new Date().toISOString()})}
export type RecipeFilters={favoriteOnly?:boolean;minRating?:number;protein?:string;mealType?:string;suitability?:string;stale?:boolean;sort?:string}
export function filterRecipes(recipes:Recipe[],query:string,filters:RecipeFilters={}){const q=query.trim().toLocaleLowerCase('sv');const filtered=recipes.filter(r=>(!q||[r.title,r.cuisine,r.primaryProtein,...r.tags,...r.ingredients.map(i=>i.name)].some(v=>v.toLocaleLowerCase('sv').includes(q)))&&(!filters.favoriteOnly||r.favorite)&&(!filters.minRating||(r.rating??0)>=filters.minRating)&&(!filters.protein||r.primaryProtein===filters.protein)&&(!filters.mealType||r.mealTypes.includes(filters.mealType))&&(!filters.suitability||r.mealPrepSuitability===filters.suitability)&&(!filters.stale||!r.lastCookedAt||Date.now()-new Date(r.lastCookedAt).getTime()>60*86400000));return [...filtered].sort((a,b)=>filters.sort==='rating'?(b.rating??-1)-(a.rating??-1):filters.sort==='favorites'?Number(b.favorite)-Number(a.favorite)||b.createdAt.localeCompare(a.createdAt):filters.sort==='lastCooked'?(b.lastCookedAt??'').localeCompare(a.lastCookedAt??''):filters.sort==='stale'?(a.lastCookedAt??'').localeCompare(b.lastCookedAt??''):filters.sort==='alpha'?a.title.localeCompare(b.title,'sv'):b.createdAt.localeCompare(a.createdAt))}
