import { useEffect, useRef, useState } from 'react'
import { CalendarDays, ChefHat, Heart, MoreHorizontal, Plus, X, Download, Upload, UserRound, ShieldCheck, Leaf } from 'lucide-react'
import { downloadBackup, importBackup, readBackupFile } from './storage/backup'
import { getSetting, setSetting } from './storage/db'
type Page='week'|'recipes'|'favorites'|'more'
const info={week:['Din matvecka','Vecka','Din nästa matvecka börjar här.','Snart kan du samla veckans måltider på ett lugnt och överskådligt sätt.'],recipes:['Samla inspiration','Recept','Din receptbank kommer att visas här.','I nästa steg bygger vi platsen för recepten du faktiskt vill laga.'],favorites:['Dina bästa val','Favoriter','Dina favoritrecept kommer att visas här.','Spara guldkornen så att vardagens middagsbeslut blir enklare.']} as const
const nav=[['week','Vecka',CalendarDays],['recipes','Recept',ChefHat],['add','Lägg till',Plus],['favorites','Favoriter',Heart],['more','Mer',MoreHorizontal]] as const
function EmptyPage({page}:{page:Exclude<Page,'more'>}){const [eyebrow,title,text,detail]=info[page];return <main className="page"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><section className="hero-card"><div className="hero-icon"><Leaf/></div><h2>{text}</h2><p>{detail}</p><div className="coming"><span/> Kommer snart</div></section><section className="tip-card"><span>En god vana i taget</span><p>Meal Prep sparar all din personliga information lokalt på den här enheten.</p></section></main>}
function MorePage(){const [name,setName]=useState('');const [status,setStatus]=useState('');const input=useRef<HTMLInputElement>(null);useEffect(()=>{void getSetting<string>('profileName').then(v=>setName(v??''))},[]);async function save(){await setSetting('profileName',name.trim());setStatus('Namnet är sparat lokalt.')}async function restore(file?:File){if(!file)return;try{const backup=await readBackupFile(file);if(!confirm('Återställningen ersätter all befintlig lokal Meal Prep-data. Vill du fortsätta?'))return;await importBackup(backup);setName(await getSetting<string>('profileName')??'');setStatus('Backupen har återställts.')}catch(e){setStatus(e instanceof Error?e.message:'Backupen kunde inte läsas.')}finally{if(input.current)input.current.value=''}}return <main className="page"><p className="eyebrow">Inställningar</p><h1>Mer</h1><section className="settings-card"><Heading icon={<UserRound/>} title="Min profil" text="Testa att lokal lagring fungerar."/><label htmlFor="name">Namn</label><input id="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Ditt namn"/><button className="primary" onClick={save}>Spara</button></section><section className="settings-card"><Heading icon={<ShieldCheck/>} title="Data & backup" text="Spara en trygg kopia av all lokal data."/><button className="secondary" onClick={()=>void downloadBackup()}><Download/>Exportera backup</button><button className="secondary" onClick={()=>input.current?.click()}><Upload/>Återställ backup</button><input ref={input} className="file-input" type="file" accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/>{status?<p className="status" role="status">{status}</p>:null}</section></main>}
function Heading({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="section-heading"><span className="small-icon">{icon}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
export default function App(){const [page,setPage]=useState<Page>(()=>{const p=location.hash.slice(1);return ['week','recipes','favorites','more'].includes(p)?p as Page:'week'});const [sheet,setSheet]=useState(false);function go(next:Page){setPage(next);location.hash=next}return <div className="app-shell"><header><div className="brand"><span><ChefHat/></span><strong>Meal Prep</strong></div><span className="local-pill">Lokalt & privat</span></header>{page==='more'?<MorePage/>:<EmptyPage page={page}/>}<nav aria-label="Huvudnavigation">{nav.map(([id,label,Icon])=>id==='add'?<button key={id} className="add-button" aria-label={label} onClick={()=>setSheet(true)}><span><Icon/></span><small>Lägg till</small></button>:<button key={id} className={page===id?'active':''} aria-current={page===id?'page':undefined} onClick={()=>go(id)}><Icon/><small>{label}</small></button>)}</nav>{sheet?<div className="overlay" onClick={()=>setSheet(false)}><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title" onClick={e=>e.stopPropagation()}><div className="handle"/><button className="close" aria-label="Stäng" onClick={()=>setSheet(false)}><X/></button><span className="sheet-icon"><Plus/></span><h2 id="sheet-title">Något gott på gång</h2><p>Import av recept kommer i nästa steg.</p><button className="primary" onClick={()=>setSheet(false)}>Jag förstår</button></section></div>:null}</div>}
